services:
  - type: web
    name: tictactoe-backend
    env: python
    buildCommand: |
      cd server
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      cd server && gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app --timeout 120 --log-level info
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
