services:
  - type: web
    name: tictactoe-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app --timeout 120 --log-level info
    healthCheckPath: /    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: JWT_SECRET_KEY
        value: your-jwt-secret-key-here
      - key: DATABASE_URL
        value: postgresql://postgres:your-password@db.your-project-id.supabase.co:6543/postgres?pgbouncer=true
      - key: SUPABASE_URL
        value: https://your-project-id.supabase.co
      - key: SUPABASE_SERVICE_KEY
        value: your-service-role-key-here
      - key: FLASK_ENV
        value: production
      - key: CLIENT_URL
        value: https://your-frontend-url.vercel.app
