services:
  - type: web
    name: tictactoe-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app --timeout 120 --log-level info
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tictactoe-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: CLIENT_URL
        value: https://your-frontend-domain.vercel.app

  - type: pgsql
    name: tictactoe-db
    databaseName: tictactoe
    user: tictactoe_user
